name: Build and Deploy to Google Cloud

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    environment: development
    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      REGION: ${{ secrets.REGION }}
      APP_NAME: ${{ secrets.DEV_APP_NAME }}
      REGISTRY_NAME: ${{ secrets.ARTIFACT_REGISTRY_NAME }}
      SERVICE_ACCOUNT_EMAIL: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
    steps:
      - name: Print environment variables
        run: |
          echo "PROJECT_ID=${{ env.PROJECT_ID }}"
          echo "REGION=${{ env.REGION }}"
          echo "APP_NAME=${{ env.APP_NAME }}"
          echo "REGISTRY_NAME=${{ env.REGISTRY_NAME }}"
          echo "SERVICE_ACCOUNT_EMAIL=${{ env.SERVICE_ACCOUNT_EMAIL }}"

      - name: Checkout
        uses: actions/checkout@v3

      # Authenticate with Google Cloud
      - id: "auth"
        uses: google-github-actions/auth@v1.1.1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # Setup gcloud CLI/SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Authorize Docker push
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and tag the docker image
        run: |-
          docker build --build-arg NODE_ENV=dev . --tag ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REGISTRY_NAME }}/${{ env.APP_NAME }}:$GITHUB_SHA

      - name: Push the image to the Google Artifact Registry (GAR)
        run: |-
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REGISTRY_NAME }}/${{ env.APP_NAME }}:$GITHUB_SHA

      - name: Deploy
        run: |-
          gcloud run deploy ${{ env.APP_NAME }} \
          --region ${{ env.REGION }} \
          --image ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REGISTRY_NAME }}/${{ env.APP_NAME }}:$GITHUB_SHA \
          --platform "managed" \
          --service-account ${{ env.SERVICE_ACCOUNT_EMAIL }} \
          --port 80 \
          --quiet
